# Generated by Django 2.2.4 on 2019-10-25 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='category',
            field=models.CharField(choices=[('Art', 'Art'), ('Design', 'Design'), ('Social Media', 'Social Media')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='image',
            field=models.ImageField(upload_to='lecture_images/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
