# Generated by Django 2.2.4 on 2019-10-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0003_auto_20191026_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='price',
            field=models.IntegerField(),
        ),
    ]
