# Generated by Django 2.2.4 on 2019-10-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('Art', 'Art'), ('Design', 'Design'), ('Social Media', 'Social Media')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='image',
            field=models.ImageField(upload_to='issue_images/'),
        ),
    ]
